### ISSUE TITLE
Error: Download gemeente per faunabeheerzone throws error

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#134]
Als je probeert de figuur te downloaden met onderstaande settings.
![image](https://user-images.githubusercontent.com/16779320/74922406-6ff6c380-53cf-11ea-897f-1eb25de8a63c.png)
krijg je na lang wachten deze melding:
![image](https://user-images.githubusercontent.com/16779320/74923363-f3fd7b00-53d0-11ea-9201-35b05bc87bcb.png)

Het probleem doet zich ook voor bij jim. De error doet zich voor in onderstaande gevallen:

- Enkel gemeente per faunabeheerzone
- Enkel de figuur
- Voor alle geselecteerde jaren
- Ook met gewijzigde periodes
- Zowel aantal als aantal/100ha
- Met of zonder geselecteerde regio

**Comment by SanderDevisscher** [comment]
cannot test locally => wait for deployment on UAT

**Comment by SanderDevisscher** [comment]
Unable to test locally

**Comment by SanderDevisscher** [comment]
Error remains also in docker (is txt now instead of html)

![image](https://user-images.githubusercontent.com/16779320/75776585-89dfc100-5d54-11ea-9826-5620f4e6a5f4.png)

In docker I get this error when I download the map:
`Killed
Warning: Error in : pandoc document conversion failed with error 137
  [No stack trace available]`

**Comment by eadriaensen** [comment]
I have most likely identified the cause of this error.
Working out a possible solution..

**Comment by eadriaensen** [comment]
@SanderDevisscher 

I implemented a different approach in which the map generation (to temporary html file) and image generation (png - in fact a screenshot of this temporary html file) are split up now. 

- map generation (to temporary html) happens while interacting with the app, in the background
- image generation (png) is now the only thing to be executed when hitting the 'Download figuur' button. This reduces the time needed to prepare the download output.

Most likely the problem faced when the app is run from the server was due to too overriding the allowed time limit to provide the file for download.

I expect everything to run well now when you run the app with docker.
Final confirmation of this approach can only be done when the new version of the app is deployed on the server.

Note: this approach is currently only implemented for grofWild, not wildSchade, since it slows down the app a bit when the user interacts with the map. As long as there are no issues in wildSchade I wouldn't change anything there.

**Comment by SanderDevisscher** [comment]
Error remains

**Comment by SanderDevisscher** [comment]
works in docker now.
After I removed all my docker images, volumes and containers and rebuild the app.
Could this be the cause ?
Anyways I can check now with version identifier #138

**Comment by mvarewyck** [comment]
Steps to have the latest (correct) version via docker:
* R build grofwild.tar.gz
* docker build (docker should automatically detect a new version of .tar.gz file and not use cache from there)
* docker run
