### ISSUE TITLE
undefined columns selected at TABEL: Gerapporteerde aantal schadegevallen per type schade

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#143]
@mvarewyck @eadriaensen while testing the new update of the app I encountered this error:
`undefined columns selected ` at TABEL: Gerapporteerde aantal schadegevallen per type schade.

The error occurs independant from regio and period selected. 

_ps I've been testing with docker_

**Comment by eadriaensen** [comment]
I can reproduce the error with the latest commit.
I will look into it.

**Comment by eadriaensen** [comment]
Should be fixed now.

The error was caused by the occurrence of a new schadeCode for "GEWAS", namely "GEWASANDR".
I added a general check to throw a warning when new schadeCodes are detected.
Currently, full name for "GEWASANDR" is spelled out as "Gewas - andere" in the app (can be changed if needed)

**Comment by SanderDevisscher** [comment]
fixed in docker
