### ISSUE TITLE
Grofwildapp exoten page does not have data

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#209]
After fixing #208 I was able to run the grofwildapp in docker but the exoten page seems to have no data. 
The grofwild page and the wildschade page both contain data. 
When looking at the docker print out the exoten page seems to have data as well (see below) but no filter subsets nor graphs/maps/tables can be made.

![image](https://user-images.githubusercontent.com/16779320/105377430-187a5c80-5c0b-11eb-80eb-b1b92bece6f5.png)

**Comment by mvarewyck** [comment]
Due to not returning anything at the end of `exoten_dutchNames()` the variable `locality` was dropped for exotenData within `loadExotenData()`.
I have fixed this, now data are loaded correctly at the Exoten page.

Note: There is a print 'All column names present', which can probably be turned off now (don't know where it comes from).

**Comment by SanderDevisscher** [comment]
Works fine now
