### ISSUE TITLE
New schadedata november 2021

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#253]
Notes when loading the latest schadedata:

> Nieuwe wildsoorten gedetecteerd in raw data: wolf, rietgans, kolgans, steenmarter, kleine rietgans, boommarter, meerkoet, NA, kauw, das, duif, egel, eekhoorn, canadese gans, kip, nijlgans, bever, marterhond, muntjak, bruine rat, buizerd, gans, torenvalk
Update schadeWildsoorten aub

> Nieuwe schade bronnen gedetecteed in raw data: E_Loket_Meldpunt schade_Poly, E_Loket_Aanvraag schadevergoeding_Poly
Update sourcesSchade.

**Comment by SanderDevisscher** [comment]
> Nieuwe wildsoorten gedetecteerd in raw data: wolf, rietgans, kolgans, steenmarter, kleine rietgans, boommarter, meerkoet, NA, kauw, das, duif, egel, eekhoorn, canadese gans, kip, nijlgans, bever, marterhond, muntjak, bruine rat, buizerd, gans, torenvalk
> Update schadeWildsoorten aub

These species (exclu. canadese gans, which is a case issue => I'll fix this in the data) can be ignored for now since they are not open for hunting under the jachtopeningbesluiten (see https://www.natuurenbos.be/wildsoorten) or alien species (to be used in the alien species portal) 

> Nieuwe schade bronnen gedetecteed in raw data: E_Loket_Meldpunt schade_Poly, E_Loket_Aanvraag schadevergoeding_Poly
> Update sourcesSchade.

These (and future) schade bronnen containing `"E_Loket"` should be grouped as E-loket data.

**Comment by SanderDevisscher** [comment]
fixed in docker
