### ISSUE TITLE
Figure 'Landkaart'

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#26]
1) The download button is for downloading the map itself -> change to 'Download figuur'
2) Add a download button for downloading the data of the map itself -> add 'Download data' next to button 'Download figuur'
3) Add a download data button for the two figures on the right side
4) The resolution of the downloaded png file is a bit low. Also, since it always downloads the entire map of Flanders (instead of the zoomed view), is it possible to crop the image in order to reduce all the grey above and below Flanders (and a bit on the sides)?

**Comment by mvarewyck** [comment]
1. OK
2. OK
3. There is already an inherent download 'screenshot' functionality for the interactive graphs (click on the camera). This allows more functionalities (e.g. save zoomed region, deselect some groups) than when we would provide explicit download button. So, I did not add button for now, ok?
![screenshot from 2017-12-01 14-35-29](https://user-images.githubusercontent.com/22143743/33487962-5e5fe088-d6af-11e7-9740-52a2ebe98a97.png)

4. Now 3x more pixels horizontally & vertically (zoom = 3 instead of 1). Reduced most of the gray in plot margins. Please let us know if we still need to crop more.

**Comment by ThomasScheppers** [comment]
3. OK
4. OK
