### ISSUE TITLE
Background data for wbe

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#265]
For the map it is asked to provide some background data per wbe:

```
korte biotoopbeschrijving:
totale oppervlakte: XXX ha   /km2
percentages: 
bos 
water
akker
grasland
bebouwd
militair
anderen

```

I guess this info will come from a seperate file: one line per year and wbe code. @SanderDevisscher Do you have an example available that can be uploaded here?
https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/218_test_wbe/reporting-grofwild/inst/extdata

**Comment by SanderDevisscher** [comment]
I've calculated these background data<sup>1</sup> for all years and wbe's (currently in PR [#757](https://github.com/inbo/backoffice-wild-analyse/pull/757) of the backoffice). I've seperated these by year into a .csv per year. If you think its better to combine them into a larger file with "one line per year and wbe code" I can allways rbind them together. 

<sup>1</sup>except data about military bases. Since I'm still looking for a usable shape/geojson. I'll add the military data as `Area_mil_m2`, `Area_mil_ha`,  `Area_mil_km2` & `perc_mil` once I found the correct shape/geojson.

**Comment by SanderDevisscher** [comment]
PS WBENr is the code that can also be found in the wbe_binnengrenzen.geojsons

**Comment by mvarewyck** [comment]
Perfect, I'll see it pass by then.
> If you think its better to combine them into a larger file with "one line per year and wbe code" I can allways rbind them together.
Both options are fine for me, We can also bind the files at our side. Anyhow, I will load all files before starting the application to speed up the app. Then all data is available when the user changes year of interest.

**Comment by SanderDevisscher** [comment]
I'll keep them separate then, I think its easier to detect erroneous changes with smaller files. The files have been uploaded see cad0305.

**Comment by SanderDevisscher** [comment]
@mvarewyck we decided to ditch the percentage military base. So this should not be included in the graph.
