### ISSUE TITLE
Habitat data for multiple regions

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#297]
For WBE we could only have 1 region. When including the habitat plot for grofwildjacht, the user can select multiple regions.
How should they be displayed in the plot?

Single region (Flanders)
![Screenshot from 2022-03-28 10-45-52](https://user-images.githubusercontent.com/22143743/160361082-008d7560-9fd6-487b-b2d9-0900cadd6fe1.png)

Multiple regions (Provinces)
![Screenshot from 2022-03-28 10-45-44](https://user-images.githubusercontent.com/22143743/160361093-a9476ebb-dba9-41a1-b180-729263a8222c.png)

1. We don't display the total numbers at the top of the bars when multiple regions. When hovering over the bar, the user can see the value.
2. Top plot has total 13629km2 and bottom plot (sum over provinces) has only 13623 km2 while both are about Flanders.

**Comment by SanderDevisscher** [comment]
> For WBE we could only have 1 region. When including the habitat plot for grofwildjacht, the user can select multiple regions. How should they be displayed in the plot?

Your sugestions look good, however I would limit the maximum number of regions displayed in this graph. Thus when the user selects more than 9 (open for discussion but if i remember correctly this is the number of colors in the inbotheme)  areas should be summed up and displayed as if they are one.  

> 1. We don't display the total numbers at the top of the bars when multiple regions. When hovering over the bar, the user can see the value.

perfect

> 2. Top plot has total 13629km2 and bottom plot (sum over provinces) has only 13623 km2 while both are about Flanders.

this is probably due to accuracy differences between the shapes. I'll look into a way to build the flanders, province and comunne areas from the ground up. areas flanders = sum(areas provinces = sum(areas comunnes)))

**Comment by mvarewyck** [comment]
Thanks for the feedback. 
For more than 9 (max unique colors) regions we display the **average** percentage and add a warning
![Screenshot from 2022-03-28 15-57-52](https://user-images.githubusercontent.com/22143743/160414492-538914b4-19e0-41c6-aded-ce0ff18e06ae.png)


For reference - the according trend plot with warning
![Screenshot from 2022-03-28 15-58-09](https://user-images.githubusercontent.com/22143743/160414510-c60a76ff-1add-47b1-8d95-98d37205d310.png)

**Comment by SanderDevisscher** [comment]
@mvarewyck does the combination functionality like with the trend plot also apply to the habitat constitution graph ? ifnot, it should ;-)
