### ISSUE TITLE
add Evolutie schademeldingen to wbepagina

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#302]
# Suggested Title
 Evolutie schademeldingen

### Position
- below schademeldingen map
### Description/Disclaimer
- nvt
### Datacolumns
- 
### Filters
- 
### Code example
```
```
### Layout example
![newplot](https://user-images.githubusercontent.com/16779320/167098812-3943bc2b-7c21-4f51-9168-3416ddce2a77.png)

### Additional Options
- Download data
- ...

**Comment by mvarewyck** [comment]
Turned out to be a bit more complex. I had to copy some info from other datasets. For future, it would be good if the file "WildSchade_georef.csv" could contain:
* WBE_Naam_Toek: to be displayed in the title of the plot
* PartijNummer: to have correct matching with the spatial data region names
* [to minor extent] DiersoortNaam: Have same capitalization as for the grofwild data (e.g. Wild zwijn instead of wild zwijn)

**Comment by SanderDevisscher** [comment]
> Turned out to be a bit more complex. I had to copy some info from other datasets. For future, it would be good if the file "WildSchade_georef.csv" could contain:
> 
> * WBE_Naam_Toek: to be displayed in the title of the plot

Schade is not directly linked to a wbe instead we georef it. So unlike with the afschotdata you can/may/must use the columns `KboNummer` & `WBE_Naam_Georef`

> * PartijNummer: to have correct matching with the spatial data region names

I'll add the PartijNummer 

> * [to minor extent] DiersoortNaam: Have same capitalization as for the grofwild data (e.g. Wild zwijn instead of wild zwijn)

I'll look into it

**Comment by SanderDevisscher** [comment]
Somehow the schade evolution graph period is not affected by the schade period but by the afschot period. This should be fixed.

**Comment by SanderDevisscher** [comment]
this is fixed

@mvarewyck closing keywords seem to not work when provided with a list :-/
