### ISSUE TITLE
wbepagina should begin @2014 not 2016

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#304]
Currently the wbepagina starts at 2016 due to the fact we have only jachtterrein info since then. But we have wbe info since 2014 so I suggest 2014 should be the data start year, not 2016. For 2014 & 2015 the map should then only display the outer limits (binnengrenzen :-p) of the wbe and omit the jachtterreinen.

**Comment by mvarewyck** [comment]
(1) I think it's due to the fact that we have no geographical data for Wild zwijn before 2016:

```
> xtabs(~ afschotjaar + wildsoort, geoData)
           wildsoort
afschotjaar Ree Wild zwijn
       2014 103          0
       2015 101          0
       2016  99         20
       2017 106         38
       2018 113         15
       2019 106         39
       2020  89         43
       2021 116         43
```       
If you select 'Ree' in the WBE page, you can see the year starts already at 2014

(2) When selecting before 2016, there is still an error in the map (probably due to missing jachtterreinen. Working on it.

**Comment by mvarewyck** [comment]
If I'm correct we decided to keep as is: show since earliest year of data: since 2014 for Ree and 2016 else.
I only need to take a look if we can force the slider to start at 2014 by default for Ree

**Comment by SanderDevisscher** [comment]
Ok

**Comment by SanderDevisscher** [comment]
this is fixed
