### ISSUE TITLE
FIGUUR: Onderkaaklengte per jaar

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#40]
1) Pas data vanaf 2014 -> slider aanpassen. Tenzij data van daarvoor gebruiken uit het meldingsformulier? -> @Fhuysent @jimcasaer 
2) Y-as laten starten op nul? Geeft nu rare resultaten door zeer nauwe Y-as
3) Smoother vervangen door 'Gemiddelde'
4) Aantal per jaar vermelden
5) Veel foutieve data in cm ipv in mm -> controle toevoegen om dit om te zetten naar mm

**Comment by Fhuysent** [comment]
1. Add possibility to switch between 'meldingsformulier' and 'INBO' or 'combined' as data source
2. For 'INBO', limit slider range from 2014-now
3. For 'combined' use 'INBO' as source when available and 'meldingsformulier otherwise.

**Comment by mvarewyck** [comment]
Answers to @ThomasScheppers 
1. See below
2. OK, although I don't think this is a good idea. Observed values are very large compared to 0, so almost empty plot now
3. OK
4. OK, added as hover text, otherwise sloppy axes when downloading figure
5. Which check do you suggest? Exclude all measurements with size < 50 (total 40 observations) or for these multiply by 10? Then still there will be unrealistic size (eg. 10 mm?)
> plotData$variable[(plotData$variable < 50)]
 [1] 16.0 23.0 19.0 16.0 12.0 14.0 15.0 26.0 17.0 16.0 14.0 16.0 15.0 16.0 29.0
[16] 14.0 12.0 13.0 17.0 10.0 16.0 14.0 16.0 16.0 15.0 14.0 16.0 15.0 14.0 14.0
[31] 15.0 16.0 15.0  7.5 17.0 14.0 18.0  1.0 14.0 15.0

Answers to @Fhuysent 
1-3. Which data variables are used therefore? I use
If from meldingsformulier: "lengte_mm"; if from INBO: "onderkaaklengte"
> head(data[, c("onderkaaklengte", "lengte_mm", "onderkaaklengte_links", "onderkaaklengte_rechts")])
  onderkaaklengte lengte_mm onderkaaklengte_links onderkaaklengte_rechts
1             140       141                   140                    140
2             150      <NA>                   150                     NA
3             127      <NA>                   127                     NA
4             161       152                   161                    161
5             157      <NA>                   157                    157
6             NaN       140                    NA                     NA

4. OK

**Comment by ThomasScheppers** [comment]
to be checked

**Comment by stijnvanhoey** [comment]
1. `< 20` -> *10  => deze *opkuis* zal mee opgenomen worden in de pre-processing door @Fhuysent 
2. `110`  tot `200` zijn de realistische waarden
3. `111` waarden dienen door @Fhuysent nagekeken te worden

Afspraak is dat deze op preprocessing kan gebeuren door @Fhuysent

**Comment by stijnvanhoey** [comment]
Column names currently `lengte_mm`; if from INBO: `onderkaaklengte`
-> should be checked by faunabeheer if this is still valid and to make sure the data columns are available.

**Comment by Yasmine-Verzelen** [comment]
@Fhuysent

**Comment by jimcasaer** [comment]
@SanderDevisscher close issue ?

**Comment by SanderDevisscher** [comment]
is van 2017 => ja
