### ISSUE TITLE
Display options for wildschade data

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#94]
* Add general option to select 'schadeBasisCode': multiple selection. Subset on these data for all the maps.
```
> table(schadeData@data$schadeBasisCode)
ANDERE  GEWAS   VRTG 
   236    447    190 
```
* Add general option to filter on 'gewas'. Variable will be created by @SanderDevisscher 
* Remove current options for 'Eenheid'. Always show 'Aantal beschadigde percelen'. 'Aantal schadegevallen' is not of interest.
* Add option 'Eenheid': Aantal or Aantal/100ha (as for grofwild)
* Add for 'Regio-schaal' the options 'Faunabeheerzone' and 'Gemeente for FBZ' (as for grofwild)

**Comment by mvarewyck** [comment]
@SanderDevisscher Could you have a look to clean up the 'gewas' variable?

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Could you have a look to clean up the 'gewas' variable?
@jimcasaer wanneer kunnen we hier eens voor samenzitten om met exploratory + R een vereenvoudigd lijstje gewassen te maken? 

Ik zal eventueel al een aanzet maken.

**Comment by SanderDevisscher** [comment]
@jimcasaer @mvarewyck I do not agree with this bullet point:

> Remove current options for 'Eenheid'. Always show 'Aantal beschadigde percelen'. 'Aantal schadegevallen' is not of interest. 

Since data included in dataset also contains traffic-accidents I think the opposite is true, the number of instances of damage is more relevant as overview then the number of damaged fields (only relevant with Type Schade == Gewas).  Therefor I suggest taking the n_distinct of `IndieningLocationID ` per Regio per Year (`Jaartal`) and renaming the map to 'Gerapporteerd aantal schadegevallen'. 

Optionally I would add the option, to the initial map, to select between 'Aantal schadegevallen' & 'Aantal schadeclaims' (& 'Aantal beschadigde percelen') 

Definitions:
----------------
-  **schadegeval:** a case of damage at a certain location caused on a certain date. `n_distinct(IndieningLocationID )`
-  **schadeclaim:** several cases of damage at several locations caused on a certain date and reported in 1 indiening.  `n_distinct(IndieningID)` 
-  **beschadigde percelen:** a case of damage to a certain field (only Type Schade == Gewas) at a certain location caused on a certain date. `filter(IndieningSchadeBasisCode == Gewas) %>% n_distinct(IndieningLocationID ) `

**Comment by SanderDevisscher** [comment]
@mvarewyck possibly a better solution is letting the title of graphs and maps be dependent on the choice of damage type in the filter data section.

 | Damage type(s) selected | type name specifier  |
|-------------------------|----------------------|
| Gewas                   | Beschadigde percelen |
| Voertuig                | Verkeersongevallen   |
| Andere                  | Schadegevallen       |
| Multiple                | Schadegevallen       |

**Comment by SanderDevisscher** [comment]
In case of aantal/100ha the title is allready "Schadegevallen". This should follow the same rules.

**Comment by mvarewyck** [comment]
If "Voertuig" is chosen, include filter for selecting "GNPERSLTSL" "PERSLTSL" "ONBEKEND"
If "Gewas" is chosen, include filter for selecting "WLSCHD"     "VRTSCHD"
Remove filter to select for "Gewas" by "SoortNaam"
